name: Integration tests

on: [push]

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-cache-

      - name: Install npm dependencies
        run: npm ci
      - name: install ts-node
        run: npm install --global ts-node
      - name: install typescript
        run: npm install --global typescript
      - name: Run tests tor
        timeout-minutes: 60
        run: DEBUG_COLORS=yes DEBUG='waggle*, nectar*' jest communityJest.test.ts